name: Get a file from Utrust's secrets repo on keybase

inputs:
  repo:
    description: 'Keybase URL to the git repo'
    required: true
  file:
    description: 'The file to get'
    required: true
  prefix:
    description: 'A prefix to name the file with'
    required: false
    default: "keybase-secret-"

outputs:
  file:
    description: 'The fetched file'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.file }}
